service: exchange-rate

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  insert:
    handler: handler.insert
    events:
      - http:
          path: exchange-rate
          method: post
          cors: true
  getAll:
    handler: handler.getAll
    events:
      - http:
          path: exchange-rate
          method: get
          cors: true
  get:
    handler: handler.get
    events:
      - http:
          path: exchange-rate/{id}
          method: get
          cors: true
  update:
    handler: handler.update
    events:
      - http:
          path: exchange-rate/{id}
          method: patch
          cors: true
  search:
    handler: handler.search
    events:
      - http:
          path: exchange-rate/search/{currency}/{date}
          method: get
          cors: true

resources:
  Resources:
    ExchangeRatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'exchange-rates' 
